chore: add 'Admin' menu item with placeholder for product maintenance
ndvo/pet-shop-manoel pull request #14
Opened 2024-12-22 15:27 UTC by manoelmndf

# What was do:

- Added 'Admin' item to the top menu  
- Linked to a placeholder page for product maintenance  
- Code refactored to allow future implementation of product listing and maintenance  
[Issue #10 ](https://github.com/ndvo/pet-shop-manoel/issues/10)

2024-12-22 15:39 UTC, ndvo requested changes
Pet-Shop link is not working on this branch.
Also, clicking on admin gives a not found page.

2024-12-22 18:38 UTC, manoelmndf commented
> Pet-Shop link is not working on this branch. Also, clicking on admin gives a not found page.

The page will be in the next pull request, now refactored to use the data from localstorage.

2024-12-23 21:57 UTC, ndvo commented
Well... but we can't merge it if it removes existing functionality.

2024-12-26 18:37 UTC, ndvo commented on assets/js/petshop.js
> +      console.log(localStorage.getItem('products'));
This shouldn't be in production.

2024-12-26 20:47 UTC, ndvo commented on assets/js/petshop.js
> +      console.log(localStorage.getItem('products'));
```suggestion
```

2024-12-27 12:58 UTC, ndvo commented on assets/js/petshop.js
> +      console.log(localStorage.getItem('products'));
```suggestion
```

2025-01-03 13:50 UTC, ndvo commented on assets/js/maintainProducts.js
> +    // Load products from localStorage
We need to avoid redundant comments.

2025-01-03 13:55 UTC, ndvo approved these changes
We should not make our files 755, that is unnecessary.
644 is the permissions we wanted.
We can change this is a follow up PR.

Also, avoid adding redundant comments.

2025-01-03 13:56 UTC, merged